// <auto-generated />
using System;
using MegaMinds_Practical.DbContextDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegaMinds_Practical.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250617174753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MegaMinds_Practical.Model.ObservationDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObservationId")
                        .HasColumnType("int");

                    b.Property<int?>("ObservationsModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SamplingTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ObservationsModelId");

                    b.ToTable("ObservationData");
                });

            modelBuilder.Entity("MegaMinds_Practical.Model.ObservationPropertiesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObservationDataId")
                        .HasColumnType("int");

                    b.Property<int?>("ObservationDataModelId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ObservationDataModelId");

                    b.ToTable("ObservationProperties");
                });

            modelBuilder.Entity("MegaMinds_Practical.Model.ObservationsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("MegaMinds_Practical.Model.ObservationDataModel", b =>
                {
                    b.HasOne("MegaMinds_Practical.Model.ObservationsModel", null)
                        .WithMany("Datas")
                        .HasForeignKey("ObservationsModelId");
                });

            modelBuilder.Entity("MegaMinds_Practical.Model.ObservationPropertiesModel", b =>
                {
                    b.HasOne("MegaMinds_Practical.Model.ObservationDataModel", null)
                        .WithMany("Properties")
                        .HasForeignKey("ObservationDataModelId");
                });

            modelBuilder.Entity("MegaMinds_Practical.Model.ObservationDataModel", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MegaMinds_Practical.Model.ObservationsModel", b =>
                {
                    b.Navigation("Datas");
                });
#pragma warning restore 612, 618
        }
    }
}
